# Test stage
FROM golang:1.24-alpine

WORKDIR /app

# Install necessary build tools and git
RUN apk add --no-cache git gcc musl-dev mysql-client

# Copy go mod and sum files
COPY go.mod go.sum ./

# Download dependencies
RUN go mod download

# Copy the source code
COPY . .

# Install test dependencies
RUN go install github.com/golang/mock/mockgen@latest
RUN go install github.com/jstemmer/go-junit-report@latest

# Generate mocks
RUN cd internal/domain/mocks && \
    mockgen -destination=task_repository_mock.go -package=mocks golangwithgin/internal/domain TaskRepository && \
    mockgen -destination=task_processor_mock.go -package=mocks golangwithgin/internal/domain TaskProcessor && \
    mockgen -destination=task_service_mock.go -package=mocks golangwithgin/internal/domain TaskService

# Run tests command will be specified in docker-compose
CMD ["go", "test", "./...", "-v", "-cover"] 