server:
  port: "8888"

database:
  host: "localhost"
  port: "3306"
  username: "test_user"
  password: "test_password"
  name: "test_db"

jwt:
  secret: "test-secret-key"
  expiration: 24h

logger:
  level: "debug"
  file: "test.log"
